version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.9

jobs:
  docker:
    executor: docker-executor
    steps:
      - checkout

      - run:
          name: Log in to Docker Hub
          command: |
            echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - run:
          name: Pull base image
          command: docker pull unixfox/searx-custom:latest

      - run:
          name: Tag and push image
          command: |
            docker tag unixfox/searx-custom:latest diogo0587/quaali:tagname
            docker push diogo0587/quaali:tagname

      - run:
          name: Run Docker image
          command: docker run -d --name searx-container -p 5000:5000 diogo0587/quaali:tagname

      - run:
          name: Wait for the container to generate the page
          command: sleep 30  # Ajuste o tempo conforme necessário para garantir que a página HTML seja gerada

      - run:
          name: Copy HTML page from container
          command: docker cp searx-container:/caminho/para/sua_pagina.html ./saida_pagina.html

      - run:
          name: Commit HTML page to repository
          command: |
            git config --global user.name 'circleci'
            git config --global user.email 'circleci@circleci.com'
            git add ./saida_pagina.html
            git commit -m 'Adiciona página HTML gerada pelo container'
            git push

workflows:
  version: 2
  build_and_push:
    jobs:
      - docker
