name: Docker Image CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "latest"
          driver: "docker-container"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: unixfox/searx-custom:latest
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}

      - name: Pull and run Docker image
        run: |
          docker pull unixfox/searx-custom:latest
          docker run -d unixfox/searx-custom:latest
