name: Docker Image CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: diogo0587/quaali:latest

      - name: Run Docker image
        run: |
          docker run -d --name searx-container -p 5000:5000 diogo0587/quaali:latest

      - name: Wait for the container to generate the page
        run: |
          timeout 30s bash -c 'until docker exec searx-container test -f /usr/local/searx/index.html; do sleep 1; done'

      - name: Copy HTML page from container
        run: docker cp searx-container:/usr/local/searx/index.html ./index.html

      - name: Remove Docker container
        run: docker rm -f searx-container

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git checkout --orphan gh-pages
          git rm -rf .
          mv index.html .
          git add index.html
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages

      # Remova ou substitua esta etapa se não for permitida
      - name: Upload HTML artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy-page
          path: index.html
