name: Docker Image CI/CD
on: 
  push: 
    branches: 
      - "main"
jobs: 
  docker: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create gh-pages branch
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan gh-pages
          git rm -rf .
          touch .nojekyll
          echo "initial commit" > README.md
          git add .nojekyll README.md
          git commit -m "Create gh-pages branch"
          git push origin gh-pages

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull base image
        run: docker pull unixfox/searx-custom:latest

      - name: Tag and push image
        run: |
          docker tag unixfox/searx-custom:latest diogo0587/quaali:latest
          docker push diogo0587/quaali:latest

      - name: Run Docker image
        run: |
          docker run -d --name searx-container -p 5000:5000 diogo0587/quaali:latest

      - name: Wait for the container to generate the page
        run: sleep 30  # Adjust the time as needed to ensure the HTML page is generated

      - name: Copy HTML page from container
        run: docker cp searx-container:/usr/local/searx ./saida_pagina.html

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email 'github-actions@github.com'
          git config --global user.name 'GitHub Actions'
          git add saida_pagina.html
          git commit -m 'Add HTML page generated by the container'
          git push origin gh-pages

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v3
        with: 
          name: deploy-page
          path: saida_pagina.html
