name: Docker Image CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull base image
        run: docker pull unixfox/searx-custom:latest

      - name: Tag and push image
        run: |
          docker tag unixfox/searx-custom:latest diogo0587/quaali:tagname
          docker push diogo0587/quaali:tagname

      - name: Run Docker image
        run: |
          docker run -d --name searx-container -p 5000:5000 diogo0587/quaali:tagname

      - name: Generate HTML page
        run: |
          echo "<html><body><h1>Deploy Successful!</h1><p>Your Docker image diogo0587/quaali:tagname is running successfully.</p><p><a href='artifacts/deploy-status'>Download Artifact</a></p></body></html>" > deploy_status.html

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v2
        with:
          name: deploy-status
          path: deploy_status.html
